import Head from 'next/head';
import { Footer } from './Footer/footer';
import { Header } from './Header/header';

export function MainLayout({children, title}){
    return(
        <div className='wrapper'>
            <Head>
                <title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
            </Head>
            <nav>
                <Header />
            </nav>
            <main className='main'>{children}</main>
            <Footer />
        </div>
    )
}